<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="0" total="14" passed="11">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="18093" started-at="2020-12-02T08:04:51Z" finished-at="2020-12-02T08:05:09Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="18093" started-at="2020-12-02T08:04:51Z" finished-at="2020-12-02T08:05:09Z">
      <class name="com.infy.updateEmployeeRecord">
        <test-method status="FAIL" signature="updateEmployee()[pri:0, instance:com.infy.updateEmployeeRecord@7f9a81e8]" name="updateEmployee" duration-ms="5255" started-at="2020-12-02T13:34:51Z" finished-at="2020-12-02T13:34:56Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [429]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [429]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testng.Assert.assertEquals(Assert.java:399)
	at com.infy.updateEmployeeRecord.updateEmployee(updateEmployeeRecord.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- updateEmployee -->
      </class> <!-- com.infy.updateEmployeeRecord -->
      <class name="com.infy.UserList">
        <test-method status="PASS" signature="getUsrList()[pri:0, instance:com.infy.UserList@58651fd0]" name="getUsrList" duration-ms="1434" started-at="2020-12-02T13:34:58Z" finished-at="2020-12-02T13:34:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getUsrList -->
      </class> <!-- com.infy.UserList -->
      <class name="com.infy.deleteEmployeeRecord">
        <test-method status="FAIL" signature="deleteEmployee()[pri:0, instance:com.infy.deleteEmployeeRecord@735b5592]" name="deleteEmployee" duration-ms="1294" started-at="2020-12-02T13:34:56Z" finished-at="2020-12-02T13:34:57Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [429]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [429]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testng.Assert.assertEquals(Assert.java:399)
	at com.infy.deleteEmployeeRecord.deleteEmployee(deleteEmployeeRecord.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteEmployee -->
      </class> <!-- com.infy.deleteEmployeeRecord -->
      <class name="com.infy.GetMethod">
        <test-method status="PASS" signature="getUsrList()[pri:0, instance:com.infy.GetMethod@4520ebad]" name="getUsrList" duration-ms="485" started-at="2020-12-02T13:34:59Z" finished-at="2020-12-02T13:34:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getUsrList -->
      </class> <!-- com.infy.GetMethod -->
      <class name="com.infy.DeleteAWSBill">
        <test-method status="PASS" signature="deleteAWSBill()[pri:0, instance:com.infy.DeleteAWSBill@5419f379]" name="deleteAWSBill" duration-ms="1942" started-at="2020-12-02T13:34:59Z" finished-at="2020-12-02T13:35:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteAWSBill -->
      </class> <!-- com.infy.DeleteAWSBill -->
      <class name="com.infy.CreateAzureCust">
        <test-method status="PASS" signature="createCust()[pri:0, instance:com.infy.CreateAzureCust@7dc7cbad]" name="createCust" duration-ms="1828" started-at="2020-12-02T13:35:01Z" finished-at="2020-12-02T13:35:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createCust -->
      </class> <!-- com.infy.CreateAzureCust -->
      <class name="com.infy.friendshipDestroy">
        <test-method status="PASS" signature="update()[pri:0, instance:com.infy.friendshipDestroy@4f933fd1]" name="update" duration-ms="638" started-at="2020-12-02T13:35:04Z" finished-at="2020-12-02T13:35:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- update -->
      </class> <!-- com.infy.friendshipDestroy -->
      <class name="com.infy.getTrends">
        <test-method status="PASS" signature="getTrends1()[pri:0, instance:com.infy.getTrends@d2cc05a]" name="getTrends1" duration-ms="634" started-at="2020-12-02T13:35:03Z" finished-at="2020-12-02T13:35:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getTrends1 -->
      </class> <!-- com.infy.getTrends -->
      <class name="com.infy.statusesUpdate">
        <test-method status="FAIL" signature="update()[pri:0, instance:com.infy.statusesUpdate@548a9f61]" name="update" duration-ms="597" started-at="2020-12-02T13:35:05Z" finished-at="2020-12-02T13:35:05Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [403] but found [400]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [403] but found [400]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testng.Assert.assertEquals(Assert.java:399)
	at com.infy.statusesUpdate.update(statusesUpdate.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- update -->
      </class> <!-- com.infy.statusesUpdate -->
      <class name="com.infy.getLocation">
        <test-method status="PASS" signature="getLocation1()[pri:0, instance:com.infy.getLocation@1753acfe]" name="getLocation1" duration-ms="435" started-at="2020-12-02T13:35:05Z" finished-at="2020-12-02T13:35:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLocation1 -->
      </class> <!-- com.infy.getLocation -->
      <class name="com.infy.DisplayAllBillConnects">
        <test-method status="PASS" signature="displayBill()[pri:0, instance:com.infy.DisplayAllBillConnects@7c16905e]" name="displayBill" duration-ms="1469" started-at="2020-12-02T13:35:06Z" finished-at="2020-12-02T13:35:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- displayBill -->
      </class> <!-- com.infy.DisplayAllBillConnects -->
      <class name="com.infy.Demo">
        <test-method status="PASS" signature="f()[pri:0, instance:com.infy.Demo@2a2d45ba]" name="f" duration-ms="451" started-at="2020-12-02T13:35:07Z" finished-at="2020-12-02T13:35:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
      </class> <!-- com.infy.Demo -->
      <class name="com.infy.friendshipUpdate">
        <test-method status="PASS" signature="destroy()[pri:0, instance:com.infy.friendshipUpdate@2a5ca609]" name="destroy" duration-ms="550" started-at="2020-12-02T13:35:07Z" finished-at="2020-12-02T13:35:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- destroy -->
      </class> <!-- com.infy.friendshipUpdate -->
      <class name="com.infy.Update">
        <test-method status="PASS" signature="getUsrList()[pri:0, instance:com.infy.Update@20e2cbe0]" name="getUsrList" duration-ms="960" started-at="2020-12-02T13:35:08Z" finished-at="2020-12-02T13:35:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getUsrList -->
      </class> <!-- com.infy.Update -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
